### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by kinglevel** [routmoute/grandMA3-linux-installer#6]
Followed all steps, i get the error:

`Illegal Instruction`

In the terminal when i try to start MA3.
Proxmox, no dedicated gpu attached, x86, Debian 12, all packages installed and updated.

**Comment by routmoute** [comment]
Grandma3 need 4 cores minimum and gpu with hardware acceleration and openGL 4.1 support..
I never tried to install it on a proxmox VM. But I already seen this error when I had only 2 cores.

**Comment by kinglevel** [comment]
ok

Suggesting editing README.md with requirements.

**Comment by routmoute** [comment]
Just see requirements on MA Lighting Website: https://help2.malighting.com/Page/grandMA3/onpc_system_requirements/en/
